[registries.crates-io]
protocol = "sparse"

[source.crates-io]
replace-with = 'bytedance'  # 或其他镜像

# 中国科学技术大学
[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

# 或清华大学
[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

# 或阿里云
[source.aliyun]
registry = "https://code.aliyun.com/rustcc/crates.io-index.git"

[source.bytedance]
registry = "sparse+https://rsproxy.cn/index/"