name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: LocalFiles-x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Run cargo build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/LocalFiles

  release-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: LocalFiles-x86_64-pc-windows-msvc.exe
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
      - name: Run cargo build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/LocalFiles.exe

  release-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            name: LocalFiles-aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
      - name: Run cargo build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/LocalFiles
